name: clang
on:
  push:
    branches: [ hotfix/attempt-to-fix-clang-ci-error ]
  pull_request:
    branches: [ master ]

jobs:

  build-clang-10-osx-stl:
    name: Clang-10 OSX - STL
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        export CC=clang
        export CXX=clang++
        export ASAN_OPTIONS=alloc_dealloc_mismatch=0,detect_leaks=0
        git fetch --tags
        cmake -D BUILD_TESTS=ON -DNO_STL=OFF -DETL_USE_TYPE_TRAITS_BUILTINS=OFF -DETL_USER_DEFINED_TYPE_TRAITS=OFF -DETL_FORCE_TEST_CPP03=OFF ./
        clang --version
        make

    - name: Run tests
      run: ./test/etl_tests

